<a href="https://colab.research.google.com/github/panda-sai/Frozen-Lake-MDP-Q-Learning/blob/master/MDP_Q_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [7]:
env = gym.make("FrozenLake-v1")

In [8]:
state = env.reset()
env.render()

In [9]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [12]:
rewards_all_episodes = []

In [13]:
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode): 
      exploration_rate_threshold = random.uniform(0, 1)
      
      if exploration_rate_threshold > exploration_rate:
          action = np.argmax(q_table[state,:]) 
      else:
          action = env.action_space.sample()

      new_state, reward, done, info = env.step(action)

      q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
      learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

      state = new_state
      rewards_current_episode += reward 

      if done == True: 
          break

    exploration_rate = min_exploration_rate + \
    (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)

    rewards_all_episodes.append(rewards_current_episode)


rewards_per_thosand_episodes = np.array_split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
print("********Average reward per thousand episodes********\n")
for r in range (0,np.array(rewards_per_thosand_episodes).shape[0]):
    print(count,  ": ",str(sum(rewards_per_thosand_episodes[r]/1000)))
    count += 1000
    
print("\n\n********Q-table********\n")
print(q_table)

********Average reward per thousand episodes********

1000 :  0.047000000000000035
2000 :  0.20000000000000015
3000 :  0.4170000000000003
4000 :  0.5550000000000004
5000 :  0.6350000000000005
6000 :  0.6280000000000004
7000 :  0.6810000000000005
8000 :  0.6820000000000005
9000 :  0.6860000000000005
10000 :  0.6680000000000005


********Q-table********

[[0.52225085 0.49022997 0.49338229 0.49001697]
 [0.35411465 0.3026747  0.14950485 0.48780989]
 [0.41081619 0.41135801 0.41447298 0.44469913]
 [0.3190297  0.25281799 0.32922453 0.43337889]
 [0.54418541 0.42276992 0.40692159 0.38281766]
 [0.         0.         0.         0.        ]
 [0.45140429 0.14821109 0.19571538 0.14750761]
 [0.         0.         0.         0.        ]
 [0.38842648 0.43515948 0.35286939 0.58500925]
 [0.43465231 0.63435502 0.3271297  0.29253699]
 [0.64658472 0.39076216 0.38531041 0.31198717]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.54140779 0.48717684 0.73891038

In [14]:
# Watch our agent play Frozen Lake by playing the best action 
# from each state according to the Q-table

for episode in range(3):
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):        
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)

        action = np.argmax(q_table[state,:])        
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
            clear_output(wait=True)
            break            
            
        state = new_state
        
env.close()

****You reached the goal!****
